# Module 12 Challenge
## Deliverable 2: Scrape and Analyze Mars Weather Data

In [1]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as soup
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
browser = Browser('chrome')

### Step 1: Visit the Website

Use automated browsing to visit the [Mars Temperature Data Site](https://static.bc-edx.com/data/web/mars_facts/temperature.html). Inspect the page to identify which elements to scrape.

   > **Hint** To identify which elements to scrape, you might want to inspect the page by using Chrome DevTools to discover whether the table contains usable classes.

In [3]:
# Visit the website
# https://static.bc-edx.com/data/web/mars_facts/temperature.html
url = "https://static.bc-edx.com/data/web/mars_facts/temperature.html"
browser.visit(url)

### Step 2: Scrape the Table

Create a Beautiful Soup object and use it to scrape the data in the HTML table.

Note that this can also be achieved by using the Pandas `read_html` function. However, use Beautiful Soup here to continue sharpening your web scraping skills.

In [4]:
# Create a Beautiful Soup Object
html = browser.html 
soup = soup(html, 'html.parser')
soup

<html lang="en"><head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="" name="description"/>
<title>Mars Temperature Data</title>
<link href="css/bootstrap.min.5.2.2.css" rel="stylesheet" type="text/css"/>
<link href="css/temp.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<main>
<div class="container py-4">
<header class="pb-3 mb-4 border-bottom">
<a class="d-flex align-items-center text-dark text-decoration-none" href="/">
<span class="fs-4">Mission To Mars</span>
</a>
</header>
<div class="p-5 mb-4 bg-light rounded-3">
<div class="container-fluid py-5">
<h1 class="display-5 fw-bold">Mars Temperature Data</h1>
<p class="col-md-8 fs-4">This is Mars data.</p>
<table class="table">
<tbody><tr>
<th>id</th>
<th>terrestrial_date</th>
<th>sol</th>
<th>ls</th>
<th>month</th>
<th>min_temp</th>
<th>pressure</th>
</tr>
<tr class="data-row">
<td>2</td>
<td>2012-08-16</td>
<td>10</td>
<td>155</td>
<td>6</td>
<td>-75.0</td>
<td>739.0</td>
</tr>
<tr class="data-row">
<td>13</td>
<td>2012-08-17</td>
<td>11</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>24</td>
<td>2012-08-18</td>
<td>12</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>35</td>
<td>2012-08-19</td>
<td>13</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>732.0</td>
</tr>
<tr class="data-row">
<td>46</td>
<td>2012-08-20</td>
<td>14</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>57</td>
<td>2012-08-21</td>
<td>15</td>
<td>158</td>
<td>6</td>
<td>-78.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>68</td>
<td>2012-08-22</td>
<td>16</td>
<td>158</td>
<td>6</td>
<td>-77.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>79</td>
<td>2012-08-23</td>
<td>17</td>
<td>159</td>
<td>6</td>
<td>-76.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>112</td>
<td>2012-08-27</td>
<td>21</td>
<td>161</td>
<td>6</td>
<td>-74.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>114</td>
<td>2012-08-28</td>
<td>22</td>
<td>162</td>
<td>6</td>
<td>-74.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>123</td>
<td>2012-08-29</td>
<td>23</td>
<td>162</td>
<td>6</td>
<td>-75.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>134</td>
<td>2012-08-30</td>
<td>24</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>145</td>
<td>2012-08-31</td>
<td>25</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>156</td>
<td>2012-09-01</td>
<td>26</td>
<td>164</td>
<td>6</td>
<td>-76.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>163</td>
<td>2012-09-02</td>
<td>27</td>
<td>164</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>170</td>
<td>2012-09-03</td>
<td>28</td>
<td>165</td>
<td>6</td>
<td>-75.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>171</td>
<td>2012-09-04</td>
<td>29</td>
<td>166</td>
<td>6</td>
<td>-75.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>172</td>
<td>2012-09-05</td>
<td>30</td>
<td>166</td>
<td>6</td>
<td>-74.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>173</td>
<td>2012-09-06</td>
<td>31</td>
<td>167</td>
<td>6</td>
<td>-74.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>175</td>
<td>2012-09-08</td>
<td>33</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>176</td>
<td>2012-09-10</td>
<td>34</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>177</td>
<td>2012-09-11</td>
<td>35</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>749.0</td>
</tr>
<tr class="data-row">
<td>178</td>
<td>2012-09-12</td>
<td>36</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>179</td>
<td>2012-09-13</td>
<td>37</td>
<td>170</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>180</td>
<td>2012-09-14</td>
<td>38</td>
<td>171</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>181</td>
<td>2012-09-15</td>
<td>39</td>
<td>171</td>
<td>6</td>
<td>-75.0</td>
<td>751.0</td>
</tr>
<tr class="data-row">
<td>182</td>
<td>2012-09-16</td>
<td>40</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>183</td>
<td>2012-09-17</td>
<td>41</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>184</td>
<td>2012-09-18</td>
<td>42</td>
<td>173</td>
<td>6</td>
<td>-75.0</td>
<td>754.0</td>
</tr>
<tr class="data-row">
<td>185</td>
<td>2012-09-19</td>
<td>43</td>
<td>173</td>
<td>6</td>
<td>-74.0</td>
<td>756.0</td>
</tr>
<tr class="data-row">
<td>186</td>
<td>2012-09-20</td>
<td>44</td>
<td>174</td>
<td>6</td>
<td>-75.0</td>
<td>757.0</td>
</tr>
<tr class="data-row">
<td>187</td>
<td>2012-09-21</td>
<td>45</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>188</td>
<td>2012-09-22</td>
<td>46</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>189</td>
<td>2012-09-23</td>
<td>47</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>190</td>
<td>2012-09-24</td>
<td>48</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>759.0</td>
</tr>
<tr class="data-row">
<td>191</td>
<td>2012-09-25</td>
<td>49</td>
<td>177</td>
<td>6</td>
<td>-74.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>192</td>
<td>2012-09-26</td>
<td>50</td>
<td>177</td>
<td>6</td>
<td>-72.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>193</td>
<td>2012-09-27</td>
<td>51</td>
<td>178</td>
<td>6</td>
<td>-76.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>194</td>
<td>2012-09-28</td>
<td>52</td>
<td>179</td>
<td>6</td>
<td>-74.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>195</td>
<td>2012-09-29</td>
<td>53</td>
<td>179</td>
<td>6</td>
<td>-71.0</td>
<td>764.0</td>
</tr>
<tr class="data-row">
<td>196</td>
<td>2012-09-30</td>
<td>54</td>
<td>180</td>
<td>7</td>
<td>-72.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>197</td>
<td>2012-10-01</td>
<td>55</td>
<td>180</td>
<td>7</td>
<td>-74.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>198</td>
<td>2012-10-02</td>
<td>56</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>768.0</td>
</tr>
<tr class="data-row">
<td>199</td>
<td>2012-10-03</td>
<td>57</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>200</td>
<td>2012-10-04</td>
<td>58</td>
<td>182</td>
<td>7</td>
<td>-74.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>201</td>
<td>2012-10-05</td>
<td>59</td>
<td>183</td>
<td>7</td>
<td>-76.0</td>
<td>771.0</td>
</tr>
<tr class="data-row">
<td>202</td>
<td>2012-10-06</td>
<td>60</td>
<td>183</td>
<td>7</td>
<td>-75.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>203</td>
<td>2012-10-07</td>
<td>61</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>204</td>
<td>2012-10-08</td>
<td>62</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>774.0</td>
</tr>
<tr class="data-row">
<td>205</td>
<td>2012-10-09</td>
<td>63</td>
<td>185</td>
<td>7</td>
<td>-73.0</td>
<td>775.0</td>
</tr>
<tr class="data-row">
<td>206</td>
<td>2012-10-10</td>
<td>64</td>
<td>186</td>
<td>7</td>
<td>-74.0</td>
<td>776.0</td>
</tr>
<tr class="data-row">
<td>207</td>
<td>2012-10-11</td>
<td>65</td>
<td>186</td>
<td>7</td>
<td>-72.0</td>
<td>777.0</td>
</tr>
<tr class="data-row">
<td>208</td>
<td>2012-10-12</td>
<td>66</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>209</td>
<td>2012-10-13</td>
<td>67</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>780.0</td>
</tr>
<tr class="data-row">
<td>210</td>
<td>2012-10-14</td>
<td>68</td>
<td>188</td>
<td>7</td>
<td>-71.0</td>
<td>781.0</td>
</tr>
<tr class="data-row">
<td>211</td>
<td>2012-10-15</td>
<td>69</td>
<td>189</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>212</td>
<td>2012-10-17</td>
<td>70</td>
<td>189</td>
<td>7</td>
<td>-72.0</td>
<td>783.0</td>
</tr>
<tr class="data-row">
<td>213</td>
<td>2012-10-18</td>
<td>71</td>
<td>190</td>
<td>7</td>
<td>-71.0</td>
<td>784.0</td>
</tr>
<tr class="data-row">
<td>214</td>
<td>2012-10-19</td>
<td>72</td>
<td>190</td>
<td>7</td>
<td>-73.0</td>
<td>785.0</td>
</tr>
<tr class="data-row">
<td>215</td>
<td>2012-10-20</td>
<td>73</td>
<td>191</td>
<td>7</td>
<td>-70.0</td>
<td>788.0</td>
</tr>
<tr class="data-row">
<td>216</td>
<td>2012-10-21</td>
<td>74</td>
<td>192</td>
<td>7</td>
<td>-72.0</td>
<td>790.0</td>
</tr>
<tr class="data-row">
<td>217</td>
<td>2012-10-22</td>
<td>75</td>
<td>192</td>
<td>7</td>
<td>-73.0</td>
<td>791.0</td>
</tr>
<tr class="data-row">
<td>218</td>
<td>2012-10-23</td>
<td>76</td>
<td>193</td>
<td>7</td>
<td>-73.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>219</td>
<td>2012-10-24</td>
<td>77</td>
<td>193</td>
<td>7</td>
<td>-71.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>220</td>
<td>2012-10-25</td>
<td>78</td>
<td>194</td>
<td>7</td>
<td>-71.0</td>
<td>793.0</td>
</tr>
<tr class="data-row">
<td>221</td>
<td>2012-10-26</td>
<td>79</td>
<td>195</td>
<td>7</td>
<td>-73.0</td>
<td>795.0</td>
</tr>
<tr class="data-row">
<td>222</td>
<td>2012-10-27</td>
<td>80</td>
<td>195</td>
<td>7</td>
<td>-70.0</td>
<td>796.0</td>
</tr>
<tr class="data-row">
<td>223</td>
<td>2012-10-28</td>
<td>81</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>798.0</td>
</tr>
<tr class="data-row">
<td>224</td>
<td>2012-10-29</td>
<td>82</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>799.0</td>
</tr>
<tr class="data-row">
<td>225</td>
<td>2012-10-30</td>
<td>83</td>
<td>197</td>
<td>7</td>
<td>-72.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>226</td>
<td>2012-10-31</td>
<td>84</td>
<td>198</td>
<td>7</td>
<td>-70.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>227</td>
<td>2012-11-01</td>
<td>85</td>
<td>198</td>
<td>7</td>
<td>-71.0</td>
<td>805.0</td>
</tr>
<tr class="data-row">
<td>228</td>
<td>2012-11-02</td>
<td>86</td>
<td>199</td>
<td>7</td>
<td>-71.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>229</td>
<td>2012-11-03</td>
<td>87</td>
<td>199</td>
<td>7</td>
<td>-70.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>230</td>
<td>2012-11-04</td>
<td>88</td>
<td>200</td>
<td>7</td>
<td>-70.0</td>
<td>811.0</td>
</tr>
<tr class="data-row">
<td>231</td>
<td>2012-11-05</td>
<td>89</td>
<td>201</td>
<td>7</td>
<td>-73.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>233</td>
<td>2012-11-06</td>
<td>90</td>
<td>201</td>
<td>7</td>
<td>-71.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>234</td>
<td>2012-11-07</td>
<td>91</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>817.0</td>
</tr>
<tr class="data-row">
<td>235</td>
<td>2012-11-08</td>
<td>92</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>820.0</td>
</tr>
<tr class="data-row">
<td>236</td>
<td>2012-11-09</td>
<td>93</td>
<td>203</td>
<td>7</td>
<td>-72.0</td>
<td>819.0</td>
</tr>
<tr class="data-row">
<td>237</td>
<td>2012-11-10</td>
<td>94</td>
<td>204</td>
<td>7</td>
<td>-70.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>238</td>
<td>2012-11-11</td>
<td>95</td>
<td>204</td>
<td>7</td>
<td>-68.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>239</td>
<td>2012-11-12</td>
<td>96</td>
<td>205</td>
<td>7</td>
<td>-71.0</td>
<td>826.0</td>
</tr>
<tr class="data-row">
<td>240</td>
<td>2012-11-13</td>
<td>97</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>241</td>
<td>2012-11-14</td>
<td>98</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>242</td>
<td>2012-11-15</td>
<td>99</td>
<td>207</td>
<td>7</td>
<td>-68.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>3</td>
<td>2012-11-16</td>
<td>100</td>
<td>207</td>
<td>7</td>
<td>-66.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>4</td>
<td>2012-11-17</td>
<td>101</td>
<td>208</td>
<td>7</td>
<td>-65.0</td>
<td>830.0</td>
</tr>
<tr class="data-row">
<td>5</td>
<td>2012-11-18</td>
<td>102</td>
<td>209</td>
<td>7</td>
<td>-67.0</td>
<td>833.0</td>
</tr>
<tr class="data-row">
<td>6</td>
<td>2012-11-19</td>
<td>103</td>
<td>209</td>
<td>7</td>
<td>-66.0</td>
<td>836.0</td>
</tr>
<tr class="data-row">
<td>7</td>
<td>2012-11-20</td>
<td>104</td>
<td>210</td>
<td>8</td>
<td>-67.0</td>
<td>838.0</td>
</tr>
<tr class="data-row">
<td>8</td>
<td>2012-11-21</td>
<td>105</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>839.0</td>
</tr>
<tr class="data-row">
<td>9</td>
<td>2012-11-23</td>
<td>106</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>841.0</td>
</tr>
<tr class="data-row">
<td>10</td>
<td>2012-11-24</td>
<td>107</td>
<td>212</td>
<td>8</td>
<td>-66.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>11</td>
<td>2012-11-25</td>
<td>108</td>
<td>212</td>
<td>8</td>
<td>-65.0</td>
<td>845.0</td>
</tr>
<tr class="data-row">
<td>12</td>
<td>2012-11-26</td>
<td>109</td>
<td>213</td>
<td>8</td>
<td>-64.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>14</td>
<td>2012-11-27</td>
<td>110</td>
<td>214</td>
<td>8</td>
<td>-65.0</td>
<td>848.0</td>
</tr>
<tr class="data-row">
<td>15</td>
<td>2012-11-28</td>
<td>111</td>
<td>214</td>
<td>8</td>
<td>-66.0</td>
<td>849.0</td>
</tr>
<tr class="data-row">
<td>16</td>
<td>2012-11-29</td>
<td>112</td>
<td>215</td>
<td>8</td>
<td>-65.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>17</td>
<td>2012-11-30</td>
<td>113</td>
<td>216</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>18</td>
<td>2012-12-01</td>
<td>114</td>
<td>216</td>
<td>8</td>
<td>-69.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>19</td>
<td>2012-12-02</td>
<td>115</td>
<td>217</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>20</td>
<td>2012-12-03</td>
<td>116</td>
<td>217</td>
<td>8</td>
<td>-67.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>21</td>
<td>2012-12-04</td>
<td>117</td>
<td>218</td>
<td>8</td>
<td>-66.0</td>
<td>861.0</td>
</tr>
<tr class="data-row">
<td>22</td>
<td>2012-12-05</td>
<td>118</td>
<td>219</td>
<td>8</td>
<td>-65.0</td>
<td>864.0</td>
</tr>
<tr class="data-row">
<td>23</td>
<td>2012-12-06</td>
<td>119</td>
<td>219</td>
<td>8</td>
<td>-66.0</td>
<td>866.0</td>
</tr>
<tr class="data-row">
<td>25</td>
<td>2012-12-07</td>
<td>120</td>
<td>220</td>
<td>8</td>
<td>-67.0</td>
<td>867.0</td>
</tr>
<tr class="data-row">
<td>26</td>
<td>2012-12-08</td>
<td>121</td>
<td>221</td>
<td>8</td>
<td>-66.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>27</td>
<td>2012-12-09</td>
<td>122</td>
<td>221</td>
<td>8</td>
<td>-65.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>28</td>
<td>2012-12-10</td>
<td>123</td>
<td>222</td>
<td>8</td>
<td>-66.0</td>
<td>875.0</td>
</tr>
<tr class="data-row">
<td>29</td>
<td>2012-12-11</td>
<td>124</td>
<td>223</td>
<td>8</td>
<td>-66.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>30</td>
<td>2012-12-12</td>
<td>125</td>
<td>223</td>
<td>8</td>
<td>-68.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>31</td>
<td>2012-12-13</td>
<td>126</td>
<td>224</td>
<td>8</td>
<td>-66.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>32</td>
<td>2012-12-14</td>
<td>127</td>
<td>224</td>
<td>8</td>
<td>-67.0</td>
<td>884.0</td>
</tr>
<tr class="data-row">
<td>33</td>
<td>2012-12-15</td>
<td>128</td>
<td>225</td>
<td>8</td>
<td>-67.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>34</td>
<td>2012-12-16</td>
<td>129</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>36</td>
<td>2012-12-17</td>
<td>130</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>37</td>
<td>2012-12-18</td>
<td>131</td>
<td>227</td>
<td>8</td>
<td>-65.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>38</td>
<td>2012-12-19</td>
<td>132</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>39</td>
<td>2012-12-20</td>
<td>133</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>891.0</td>
</tr>
<tr class="data-row">
<td>40</td>
<td>2012-12-21</td>
<td>134</td>
<td>229</td>
<td>8</td>
<td>-67.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>41</td>
<td>2012-12-22</td>
<td>135</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>894.0</td>
</tr>
<tr class="data-row">
<td>42</td>
<td>2012-12-23</td>
<td>136</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>897.0</td>
</tr>
<tr class="data-row">
<td>43</td>
<td>2012-12-24</td>
<td>137</td>
<td>231</td>
<td>8</td>
<td>-64.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>44</td>
<td>2012-12-25</td>
<td>138</td>
<td>232</td>
<td>8</td>
<td>-65.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>45</td>
<td>2012-12-26</td>
<td>139</td>
<td>232</td>
<td>8</td>
<td>-66.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>47</td>
<td>2012-12-27</td>
<td>140</td>
<td>233</td>
<td>8</td>
<td>-66.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>48</td>
<td>2012-12-28</td>
<td>141</td>
<td>233</td>
<td>8</td>
<td>-64.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>49</td>
<td>2012-12-29</td>
<td>142</td>
<td>234</td>
<td>8</td>
<td>-65.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>50</td>
<td>2012-12-31</td>
<td>143</td>
<td>235</td>
<td>8</td>
<td>-63.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>51</td>
<td>2013-01-01</td>
<td>144</td>
<td>235</td>
<td>8</td>
<td>-64.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>52</td>
<td>2013-01-02</td>
<td>145</td>
<td>236</td>
<td>8</td>
<td>-64.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>53</td>
<td>2013-01-03</td>
<td>146</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>54</td>
<td>2013-01-04</td>
<td>147</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>55</td>
<td>2013-01-05</td>
<td>148</td>
<td>238</td>
<td>8</td>
<td>-65.0</td>
<td>912.0</td>
</tr>
<tr class="data-row">
<td>56</td>
<td>2013-01-06</td>
<td>149</td>
<td>239</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>58</td>
<td>2013-01-07</td>
<td>150</td>
<td>239</td>
<td>8</td>
<td>-64.0</td>
<td>913.0</td>
</tr>
<tr class="data-row">
<td>59</td>
<td>2013-01-08</td>
<td>151</td>
<td>240</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>60</td>
<td>2013-01-09</td>
<td>152</td>
<td>241</td>
<td>9</td>
<td>-63.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>61</td>
<td>2013-01-10</td>
<td>153</td>
<td>241</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>62</td>
<td>2013-01-11</td>
<td>154</td>
<td>242</td>
<td>9</td>
<td>-65.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>63</td>
<td>2013-01-12</td>
<td>155</td>
<td>243</td>
<td>9</td>
<td>-64.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>64</td>
<td>2013-01-13</td>
<td>156</td>
<td>243</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>65</td>
<td>2013-01-14</td>
<td>157</td>
<td>244</td>
<td>9</td>
<td>-64.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>66</td>
<td>2013-01-15</td>
<td>158</td>
<td>245</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>67</td>
<td>2013-01-16</td>
<td>159</td>
<td>245</td>
<td>9</td>
<td>-65.0</td>
<td>918.0</td>
</tr>
<tr class="data-row">
<td>69</td>
<td>2013-01-17</td>
<td>160</td>
<td>246</td>
<td>9</td>
<td>-67.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>70</td>
<td>2013-01-18</td>
<td>161</td>
<td>246</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>71</td>
<td>2013-01-19</td>
<td>162</td>
<td>247</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>72</td>
<td>2013-01-20</td>
<td>163</td>
<td>248</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>73</td>
<td>2013-01-21</td>
<td>164</td>

In [5]:
# Extract all rows of data
table = soup.find('table', class_='table')
print(table)

<table class="table">
<tbody><tr>
<th>id</th>
<th>terrestrial_date</th>
<th>sol</th>
<th>ls</th>
<th>month</th>
<th>min_temp</th>
<th>pressure</th>
</tr>
<tr class="data-row">
<td>2</td>
<td>2012-08-16</td>
<td>10</td>
<td>155</td>
<td>6</td>
<td>-75.0</td>
<td>739.0</td>
</tr>
<tr class="data-row">
<td>13</td>
<td>2012-08-17</td>
<td>11</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>24</td>
<td>2012-08-18</td>
<td>12</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>35</td>
<td>2012-08-19</td>
<td>13</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>732.0</td>
</tr>
<tr class="data-row">
<td>46</td>
<td>2012-08-20</td>
<td>14</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>57</td>
<td>2012-08-21</td>
<td>15</td>
<td>158</td>
<td>6</td>
<td>-78.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>68</td>
<td>2012-08-22</td>
<td>16</td>
<td>158</td>
<td>6</td>
<td>-77.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>79</td>
<td>2012-08-23</td>
<td>17</td>
<td>159</td>
<td>6</td>
<td>-76.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>112</td>
<td>2012-08-27</td>
<td>21</td>
<td>161</td>
<td>6</td>
<td>-74.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>114</td>
<td>2012-08-28</td>
<td>22</td>
<td>162</td>
<td>6</td>
<td>-74.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>123</td>
<td>2012-08-29</td>
<td>23</td>
<td>162</td>
<td>6</td>
<td>-75.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>134</td>
<td>2012-08-30</td>
<td>24</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>145</td>
<td>2012-08-31</td>
<td>25</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>156</td>
<td>2012-09-01</td>
<td>26</td>
<td>164</td>
<td>6</td>
<td>-76.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>163</td>
<td>2012-09-02</td>
<td>27</td>
<td>164</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>170</td>
<td>2012-09-03</td>
<td>28</td>
<td>165</td>
<td>6</td>
<td>-75.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>171</td>
<td>2012-09-04</td>
<td>29</td>
<td>166</td>
<td>6</td>
<td>-75.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>172</td>
<td>2012-09-05</td>
<td>30</td>
<td>166</td>
<td>6</td>
<td>-74.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>173</td>
<td>2012-09-06</td>
<td>31</td>
<td>167</td>
<td>6</td>
<td>-74.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>175</td>
<td>2012-09-08</td>
<td>33</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>176</td>
<td>2012-09-10</td>
<td>34</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>177</td>
<td>2012-09-11</td>
<td>35</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>749.0</td>
</tr>
<tr class="data-row">
<td>178</td>
<td>2012-09-12</td>
<td>36</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>179</td>
<td>2012-09-13</td>
<td>37</td>
<td>170</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>180</td>
<td>2012-09-14</td>
<td>38</td>
<td>171</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>181</td>
<td>2012-09-15</td>
<td>39</td>
<td>171</td>
<td>6</td>
<td>-75.0</td>
<td>751.0</td>
</tr>
<tr class="data-row">
<td>182</td>
<td>2012-09-16</td>
<td>40</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>183</td>
<td>2012-09-17</td>
<td>41</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>184</td>
<td>2012-09-18</td>
<td>42</td>
<td>173</td>
<td>6</td>
<td>-75.0</td>
<td>754.0</td>
</tr>
<tr class="data-row">
<td>185</td>
<td>2012-09-19</td>
<td>43</td>
<td>173</td>
<td>6</td>
<td>-74.0</td>
<td>756.0</td>
</tr>
<tr class="data-row">
<td>186</td>
<td>2012-09-20</td>
<td>44</td>
<td>174</td>
<td>6</td>
<td>-75.0</td>
<td>757.0</td>
</tr>
<tr class="data-row">
<td>187</td>
<td>2012-09-21</td>
<td>45</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>188</td>
<td>2012-09-22</td>
<td>46</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>189</td>
<td>2012-09-23</td>
<td>47</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>190</td>
<td>2012-09-24</td>
<td>48</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>759.0</td>
</tr>
<tr class="data-row">
<td>191</td>
<td>2012-09-25</td>
<td>49</td>
<td>177</td>
<td>6</td>
<td>-74.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>192</td>
<td>2012-09-26</td>
<td>50</td>
<td>177</td>
<td>6</td>
<td>-72.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>193</td>
<td>2012-09-27</td>
<td>51</td>
<td>178</td>
<td>6</td>
<td>-76.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>194</td>
<td>2012-09-28</td>
<td>52</td>
<td>179</td>
<td>6</td>
<td>-74.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>195</td>
<td>2012-09-29</td>
<td>53</td>
<td>179</td>
<td>6</td>
<td>-71.0</td>
<td>764.0</td>
</tr>
<tr class="data-row">
<td>196</td>
<td>2012-09-30</td>
<td>54</td>
<td>180</td>
<td>7</td>
<td>-72.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>197</td>
<td>2012-10-01</td>
<td>55</td>
<td>180</td>
<td>7</td>
<td>-74.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>198</td>
<td>2012-10-02</td>
<td>56</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>768.0</td>
</tr>
<tr class="data-row">
<td>199</td>
<td>2012-10-03</td>
<td>57</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>200</td>
<td>2012-10-04</td>
<td>58</td>
<td>182</td>
<td>7</td>
<td>-74.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>201</td>
<td>2012-10-05</td>
<td>59</td>
<td>183</td>
<td>7</td>
<td>-76.0</td>
<td>771.0</td>
</tr>
<tr class="data-row">
<td>202</td>
<td>2012-10-06</td>
<td>60</td>
<td>183</td>
<td>7</td>
<td>-75.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>203</td>
<td>2012-10-07</td>
<td>61</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>204</td>
<td>2012-10-08</td>
<td>62</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>774.0</td>
</tr>
<tr class="data-row">
<td>205</td>
<td>2012-10-09</td>
<td>63</td>
<td>185</td>
<td>7</td>
<td>-73.0</td>
<td>775.0</td>
</tr>
<tr class="data-row">
<td>206</td>
<td>2012-10-10</td>
<td>64</td>
<td>186</td>
<td>7</td>
<td>-74.0</td>
<td>776.0</td>
</tr>
<tr class="data-row">
<td>207</td>
<td>2012-10-11</td>
<td>65</td>
<td>186</td>
<td>7</td>
<td>-72.0</td>
<td>777.0</td>
</tr>
<tr class="data-row">
<td>208</td>
<td>2012-10-12</td>
<td>66</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>209</td>
<td>2012-10-13</td>
<td>67</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>780.0</td>
</tr>
<tr class="data-row">
<td>210</td>
<td>2012-10-14</td>
<td>68</td>
<td>188</td>
<td>7</td>
<td>-71.0</td>
<td>781.0</td>
</tr>
<tr class="data-row">
<td>211</td>
<td>2012-10-15</td>
<td>69</td>
<td>189</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>212</td>
<td>2012-10-17</td>
<td>70</td>
<td>189</td>
<td>7</td>
<td>-72.0</td>
<td>783.0</td>
</tr>
<tr class="data-row">
<td>213</td>
<td>2012-10-18</td>
<td>71</td>
<td>190</td>
<td>7</td>
<td>-71.0</td>
<td>784.0</td>
</tr>
<tr class="data-row">
<td>214</td>
<td>2012-10-19</td>
<td>72</td>
<td>190</td>
<td>7</td>
<td>-73.0</td>
<td>785.0</td>
</tr>
<tr class="data-row">
<td>215</td>
<td>2012-10-20</td>
<td>73</td>
<td>191</td>
<td>7</td>
<td>-70.0</td>
<td>788.0</td>
</tr>
<tr class="data-row">
<td>216</td>
<td>2012-10-21</td>
<td>74</td>
<td>192</td>
<td>7</td>
<td>-72.0</td>
<td>790.0</td>
</tr>
<tr class="data-row">
<td>217</td>
<td>2012-10-22</td>
<td>75</td>
<td>192</td>
<td>7</td>
<td>-73.0</td>
<td>791.0</td>
</tr>
<tr class="data-row">
<td>218</td>
<td>2012-10-23</td>
<td>76</td>
<td>193</td>
<td>7</td>
<td>-73.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>219</td>
<td>2012-10-24</td>
<td>77</td>
<td>193</td>
<td>7</td>
<td>-71.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>220</td>
<td>2012-10-25</td>
<td>78</td>
<td>194</td>
<td>7</td>
<td>-71.0</td>
<td>793.0</td>
</tr>
<tr class="data-row">
<td>221</td>
<td>2012-10-26</td>
<td>79</td>
<td>195</td>
<td>7</td>
<td>-73.0</td>
<td>795.0</td>
</tr>
<tr class="data-row">
<td>222</td>
<td>2012-10-27</td>
<td>80</td>
<td>195</td>
<td>7</td>
<td>-70.0</td>
<td>796.0</td>
</tr>
<tr class="data-row">
<td>223</td>
<td>2012-10-28</td>
<td>81</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>798.0</td>
</tr>
<tr class="data-row">
<td>224</td>
<td>2012-10-29</td>
<td>82</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>799.0</td>
</tr>
<tr class="data-row">
<td>225</td>
<td>2012-10-30</td>
<td>83</td>
<td>197</td>
<td>7</td>
<td>-72.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>226</td>
<td>2012-10-31</td>
<td>84</td>
<td>198</td>
<td>7</td>
<td>-70.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>227</td>
<td>2012-11-01</td>
<td>85</td>
<td>198</td>
<td>7</td>
<td>-71.0</td>
<td>805.0</td>
</tr>
<tr class="data-row">
<td>228</td>
<td>2012-11-02</td>
<td>86</td>
<td>199</td>
<td>7</td>
<td>-71.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>229</td>
<td>2012-11-03</td>
<td>87</td>
<td>199</td>
<td>7</td>
<td>-70.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>230</td>
<td>2012-11-04</td>
<td>88</td>
<td>200</td>
<td>7</td>
<td>-70.0</td>
<td>811.0</td>
</tr>
<tr class="data-row">
<td>231</td>
<td>2012-11-05</td>
<td>89</td>
<td>201</td>
<td>7</td>
<td>-73.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>233</td>
<td>2012-11-06</td>
<td>90</td>
<td>201</td>
<td>7</td>
<td>-71.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>234</td>
<td>2012-11-07</td>
<td>91</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>817.0</td>
</tr>
<tr class="data-row">
<td>235</td>
<td>2012-11-08</td>
<td>92</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>820.0</td>
</tr>
<tr class="data-row">
<td>236</td>
<td>2012-11-09</td>
<td>93</td>
<td>203</td>
<td>7</td>
<td>-72.0</td>
<td>819.0</td>
</tr>
<tr class="data-row">
<td>237</td>
<td>2012-11-10</td>
<td>94</td>
<td>204</td>
<td>7</td>
<td>-70.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>238</td>
<td>2012-11-11</td>
<td>95</td>
<td>204</td>
<td>7</td>
<td>-68.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>239</td>
<td>2012-11-12</td>
<td>96</td>
<td>205</td>
<td>7</td>
<td>-71.0</td>
<td>826.0</td>
</tr>
<tr class="data-row">
<td>240</td>
<td>2012-11-13</td>
<td>97</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>241</td>
<td>2012-11-14</td>
<td>98</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>242</td>
<td>2012-11-15</td>
<td>99</td>
<td>207</td>
<td>7</td>
<td>-68.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>3</td>
<td>2012-11-16</td>
<td>100</td>
<td>207</td>
<td>7</td>
<td>-66.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>4</td>
<td>2012-11-17</td>
<td>101</td>
<td>208</td>
<td>7</td>
<td>-65.0</td>
<td>830.0</td>
</tr>
<tr class="data-row">
<td>5</td>
<td>2012-11-18</td>
<td>102</td>
<td>209</td>
<td>7</td>
<td>-67.0</td>
<td>833.0</td>
</tr>
<tr class="data-row">
<td>6</td>
<td>2012-11-19</td>
<td>103</td>
<td>209</td>
<td>7</td>
<td>-66.0</td>
<td>836.0</td>
</tr>
<tr class="data-row">
<td>7</td>
<td>2012-11-20</td>
<td>104</td>
<td>210</td>
<td>8</td>
<td>-67.0</td>
<td>838.0</td>
</tr>
<tr class="data-row">
<td>8</td>
<td>2012-11-21</td>
<td>105</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>839.0</td>
</tr>
<tr class="data-row">
<td>9</td>
<td>2012-11-23</td>
<td>106</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>841.0</td>
</tr>
<tr class="data-row">
<td>10</td>
<td>2012-11-24</td>
<td>107</td>
<td>212</td>
<td>8</td>
<td>-66.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>11</td>
<td>2012-11-25</td>
<td>108</td>
<td>212</td>
<td>8</td>
<td>-65.0</td>
<td>845.0</td>
</tr>
<tr class="data-row">
<td>12</td>
<td>2012-11-26</td>
<td>109</td>
<td>213</td>
<td>8</td>
<td>-64.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>14</td>
<td>2012-11-27</td>
<td>110</td>
<td>214</td>
<td>8</td>
<td>-65.0</td>
<td>848.0</td>
</tr>
<tr class="data-row">
<td>15</td>
<td>2012-11-28</td>
<td>111</td>
<td>214</td>
<td>8</td>
<td>-66.0</td>
<td>849.0</td>
</tr>
<tr class="data-row">
<td>16</td>
<td>2012-11-29</td>
<td>112</td>
<td>215</td>
<td>8</td>
<td>-65.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>17</td>
<td>2012-11-30</td>
<td>113</td>
<td>216</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>18</td>
<td>2012-12-01</td>
<td>114</td>
<td>216</td>
<td>8</td>
<td>-69.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>19</td>
<td>2012-12-02</td>
<td>115</td>
<td>217</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>20</td>
<td>2012-12-03</td>
<td>116</td>
<td>217</td>
<td>8</td>
<td>-67.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>21</td>
<td>2012-12-04</td>
<td>117</td>
<td>218</td>
<td>8</td>
<td>-66.0</td>
<td>861.0</td>
</tr>
<tr class="data-row">
<td>22</td>
<td>2012-12-05</td>
<td>118</td>
<td>219</td>
<td>8</td>
<td>-65.0</td>
<td>864.0</td>
</tr>
<tr class="data-row">
<td>23</td>
<td>2012-12-06</td>
<td>119</td>
<td>219</td>
<td>8</td>
<td>-66.0</td>
<td>866.0</td>
</tr>
<tr class="data-row">
<td>25</td>
<td>2012-12-07</td>
<td>120</td>
<td>220</td>
<td>8</td>
<td>-67.0</td>
<td>867.0</td>
</tr>
<tr class="data-row">
<td>26</td>
<td>2012-12-08</td>
<td>121</td>
<td>221</td>
<td>8</td>
<td>-66.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>27</td>
<td>2012-12-09</td>
<td>122</td>
<td>221</td>
<td>8</td>
<td>-65.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>28</td>
<td>2012-12-10</td>
<td>123</td>
<td>222</td>
<td>8</td>
<td>-66.0</td>
<td>875.0</td>
</tr>
<tr class="data-row">
<td>29</td>
<td>2012-12-11</td>
<td>124</td>
<td>223</td>
<td>8</td>
<td>-66.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>30</td>
<td>2012-12-12</td>
<td>125</td>
<td>223</td>
<td>8</td>
<td>-68.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>31</td>
<td>2012-12-13</td>
<td>126</td>
<td>224</td>
<td>8</td>
<td>-66.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>32</td>
<td>2012-12-14</td>
<td>127</td>
<td>224</td>
<td>8</td>
<td>-67.0</td>
<td>884.0</td>
</tr>
<tr class="data-row">
<td>33</td>
<td>2012-12-15</td>
<td>128</td>
<td>225</td>
<td>8</td>
<td>-67.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>34</td>
<td>2012-12-16</td>
<td>129</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>36</td>
<td>2012-12-17</td>
<td>130</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>37</td>
<td>2012-12-18</td>
<td>131</td>
<td>227</td>
<td>8</td>
<td>-65.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>38</td>
<td>2012-12-19</td>
<td>132</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>39</td>
<td>2012-12-20</td>
<td>133</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>891.0</td>
</tr>
<tr class="data-row">
<td>40</td>
<td>2012-12-21</td>
<td>134</td>
<td>229</td>
<td>8</td>
<td>-67.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>41</td>
<td>2012-12-22</td>
<td>135</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>894.0</td>
</tr>
<tr class="data-row">
<td>42</td>
<td>2012-12-23</td>
<td>136</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>897.0</td>
</tr>
<tr class="data-row">
<td>43</td>
<td>2012-12-24</td>
<td>137</td>
<td>231</td>
<td>8</td>
<td>-64.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>44</td>
<td>2012-12-25</td>
<td>138</td>
<td>232</td>
<td>8</td>
<td>-65.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>45</td>
<td>2012-12-26</td>
<td>139</td>
<td>232</td>
<td>8</td>
<td>-66.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>47</td>
<td>2012-12-27</td>
<td>140</td>
<td>233</td>
<td>8</td>
<td>-66.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>48</td>
<td>2012-12-28</td>
<td>141</td>
<td>233</td>
<td>8</td>
<td>-64.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>49</td>
<td>2012-12-29</td>
<td>142</td>
<td>234</td>
<td>8</td>
<td>-65.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>50</td>
<td>2012-12-31</td>
<td>143</td>
<td>235</td>
<td>8</td>
<td>-63.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>51</td>
<td>2013-01-01</td>
<td>144</td>
<td>235</td>
<td>8</td>
<td>-64.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>52</td>
<td>2013-01-02</td>
<td>145</td>
<td>236</td>
<td>8</td>
<td>-64.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>53</td>
<td>2013-01-03</td>
<td>146</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>54</td>
<td>2013-01-04</td>
<td>147</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>55</td>
<td>2013-01-05</td>
<td>148</td>
<td>238</td>
<td>8</td>
<td>-65.0</td>
<td>912.0</td>
</tr>
<tr class="data-row">
<td>56</td>
<td>2013-01-06</td>
<td>149</td>
<td>239</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>58</td>
<td>2013-01-07</td>
<td>150</td>
<td>239</td>
<td>8</td>
<td>-64.0</td>
<td>913.0</td>
</tr>
<tr class="data-row">
<td>59</td>
<td>2013-01-08</td>
<td>151</td>
<td>240</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>60</td>
<td>2013-01-09</td>
<td>152</td>
<td>241</td>
<td>9</td>
<td>-63.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>61</td>
<td>2013-01-10</td>
<td>153</td>
<td>241</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>62</td>
<td>2013-01-11</td>
<td>154</td>
<td>242</td>
<td>9</td>
<td>-65.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>63</td>
<td>2013-01-12</td>
<td>155</td>
<td>243</td>
<td>9</td>
<td>-64.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>64</td>
<td>2013-01-13</td>
<td>156</td>
<td>243</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>65</td>
<td>2013-01-14</td>
<td>157</td>
<td>244</td>
<td>9</td>
<td>-64.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>66</td>
<td>2013-01-15</td>
<td>158</td>
<td>245</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>67</td>
<td>2013-01-16</td>
<td>159</td>
<td>245</td>
<td>9</td>
<td>-65.0</td>
<td>918.0</td>
</tr>
<tr class="data-row">
<td>69</td>
<td>2013-01-17</td>
<td>160</td>
<td>246</td>
<td>9</td>
<td>-67.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>70</td>
<td>2013-01-18</td>
<td>161</td>
<td>246</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>71</td>
<td>2013-01-19</td>
<td>162</td>
<td>247</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>72</td>
<td>2013-01-20</td>
<td>163</td>
<td>248</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>73</td>
<td>2013-01-21</td>
<td>164</td>
<td>248</td>
<td>9</td>
<td>-64.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>74</td>
<td>2013-01-22</td>
<td>165</td>
<td>249</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>75</td>
<td>2013-01-23</td>
<td>166</td>
<td>250</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>76</td>
<td>2013-01-24</td>
<td>167</td>
<td>250</td>
<td>9</td>
<td>-65.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>77</td>
<td>2013-01-25</td>
<td>168</td>
<td>251</td>
<td>9</td>
<td>-66.0</td>
<td>923.0</td>
</tr>
<tr class="data-row">
<td>78</td>
<td>2013-01-26</td>
<td>169</td>
<td>252</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>80</td>

### Step 3: Store the Data

Assemble the scraped data into a Pandas DataFrame. The columns should have the same headings as the table on the website. Here’s an explanation of the column headings:

* `id`: the identification number of a single transmission from the Curiosity rover
* `terrestrial_date`: the date on Earth
* `sol`: the number of elapsed sols (Martian days) since Curiosity landed on Mars
* `ls`: the solar longitude
* `month`: the Martian month
* `min_temp`: the minimum temperature, in Celsius, of a single Martian day (sol)
* `pressure`: The atmospheric pressure at Curiosity's location

In [6]:
mars_facts = []
rows = table.find_all('tr')

# Loop through the rows
for row in rows:
    # Find all 'td' elements within the current row
    data_cells = row.find_all('td')

    # Extract 'th' text (if available) as row heading
    row_heading = row.find('th').text if row.find('th') else ""
    row_data = {}

    # Loop through 'td' elements and add them to the mars_facts dictionary
    for index, data_cell in enumerate(data_cells):
        # Use a combination of row_heading and index to create a unique key
        key = f"{row_heading}_col{index + 1}"
        row_data[key] = data_cell.text.strip()

    mars_facts.append(row_data)

#print 
print(mars_facts)

[{}, {'_col1': '2', '_col2': '2012-08-16', '_col3': '10', '_col4': '155', '_col5': '6', '_col6': '-75.0', '_col7': '739.0'}, {'_col1': '13', '_col2': '2012-08-17', '_col3': '11', '_col4': '156', '_col5': '6', '_col6': '-76.0', '_col7': '740.0'}, {'_col1': '24', '_col2': '2012-08-18', '_col3': '12', '_col4': '156', '_col5': '6', '_col6': '-76.0', '_col7': '741.0'}, {'_col1': '35', '_col2': '2012-08-19', '_col3': '13', '_col4': '157', '_col5': '6', '_col6': '-74.0', '_col7': '732.0'}, {'_col1': '46', '_col2': '2012-08-20', '_col3': '14', '_col4': '157', '_col5': '6', '_col6': '-74.0', '_col7': '740.0'}, {'_col1': '57', '_col2': '2012-08-21', '_col3': '15', '_col4': '158', '_col5': '6', '_col6': '-78.0', '_col7': '740.0'}, {'_col1': '68', '_col2': '2012-08-22', '_col3': '16', '_col4': '158', '_col5': '6', '_col6': '-77.0', '_col7': '740.0'}, {'_col1': '79', '_col2': '2012-08-23', '_col3': '17', '_col4': '159', '_col5': '6', '_col6': '-76.0', '_col7': '742.0'}, {'_col1': '112', '_col2': '2012-08-27', '_col3': '21', '_col4': '161', '_col5': '6', '_col6': '-74.0', '_col7': '741.0'}, {'_col1': '114', '_col2': '2012-08-28', '_col3': '22', '_col4': '162', '_col5': '6', '_col6': '-74.0', '_col7': '742.0'}, {'_col1': '123', '_col2': '2012-08-29', '_col3': '23', '_col4': '162', '_col5': '6', '_col6': '-75.0', '_col7': '741.0'}, {'_col1': '134', '_col2': '2012-08-30', '_col3': '24', '_col4': '163', '_col5': '6', '_col6': '-75.0', '_col7': '742.0'}, {'_col1': '145', '_col2': '2012-08-31', '_col3': '25', '_col4': '163', '_col5': '6', '_col6': '-75.0', '_col7': '743.0'}, {'_col1': '156', '_col2': '2012-09-01', '_col3': '26', '_col4': '164', '_col5': '6', '_col6': '-76.0', '_col7': '745.0'}, {'_col1': '163', '_col2': '2012-09-02', '_col3': '27', '_col4': '164', '_col5': '6', '_col6': '-75.0', '_col7': '743.0'}, {'_col1': '170', '_col2': '2012-09-03', '_col3': '28', '_col4': '165', '_col5': '6', '_col6': '-75.0', '_col7': '745.0'}, {'_col1': '171', '_col2': '2012-09-04', '_col3': '29', '_col4': '166', '_col5': '6', '_col6': '-75.0', '_col7': '747.0'}, {'_col1': '172', '_col2': '2012-09-05', '_col3': '30', '_col4': '166', '_col5': '6', '_col6': '-74.0', '_col7': '747.0'}, {'_col1': '173', '_col2': '2012-09-06', '_col3': '31', '_col4': '167', '_col5': '6', '_col6': '-74.0', '_col7': '745.0'}, {'_col1': '175', '_col2': '2012-09-08', '_col3': '33', '_col4': '168', '_col5': '6', '_col6': '-73.0', '_col7': '748.0'}, {'_col1': '176', '_col2': '2012-09-10', '_col3': '34', '_col4': '168', '_col5': '6', '_col6': '-73.0', '_col7': '748.0'}, {'_col1': '177', '_col2': '2012-09-11', '_col3': '35', '_col4': '169', '_col5': '6', '_col6': '-73.0', '_col7': '749.0'}, {'_col1': '178', '_col2': '2012-09-12', '_col3': '36', '_col4': '169', '_col5': '6', '_col6': '-73.0', '_col7': '750.0'}, {'_col1': '179', '_col2': '2012-09-13', '_col3': '37', '_col4': '170', '_col5': '6', '_col6': '-73.0', '_col7': '750.0'}, {'_col1': '180', '_col2': '2012-09-14', '_col3': '38', '_col4': '171', '_col5': '6', '_col6': '-73.0', '_col7': '750.0'}, {'_col1': '181', '_col2': '2012-09-15', '_col3': '39', '_col4': '171', '_col5': '6', '_col6': '-75.0', '_col7': '751.0'}, {'_col1': '182', '_col2': '2012-09-16', '_col3': '40', '_col4': '172', '_col5': '6', '_col6': '-75.0', '_col7': '753.0'}, {'_col1': '183', '_col2': '2012-09-17', '_col3': '41', '_col4': '172', '_col5': '6', '_col6': '-75.0', '_col7': '753.0'}, {'_col1': '184', '_col2': '2012-09-18', '_col3': '42', '_col4': '173', '_col5': '6', '_col6': '-75.0', '_col7': '754.0'}, {'_col1': '185', '_col2': '2012-09-19', '_col3': '43', '_col4': '173', '_col5': '6', '_col6': '-74.0', '_col7': '756.0'}, {'_col1': '186', '_col2': '2012-09-20', '_col3': '44', '_col4': '174', '_col5': '6', '_col6': '-75.0', '_col7': '757.0'}, {'_col1': '187', '_col2': '2012-09-21', '_col3': '45', '_col4': '175', '_col5': '6', '_col6': '-74.0', '_col7': '758.0'}, {'_col1': '188', '_col2': '2012-09-22', '_col3': '46', '_col4': '175', '_col5': '6', '_col6': '-74.0', '_col7': '758.0'}, {'_col1': '189', '_col2': '2012-09-23', '_col3': '47', '_col4': '176', '_col5': '6', '_col6': '-75.0', '_col7': '758.0'}, {'_col1': '190', '_col2': '2012-09-24', '_col3': '48', '_col4': '176', '_col5': '6', '_col6': '-75.0', '_col7': '759.0'}, {'_col1': '191', '_col2': '2012-09-25', '_col3': '49', '_col4': '177', '_col5': '6', '_col6': '-74.0', '_col7': '761.0'}, {'_col1': '192', '_col2': '2012-09-26', '_col3': '50', '_col4': '177', '_col5': '6', '_col6': '-72.0', '_col7': '761.0'}, {'_col1': '193', '_col2': '2012-09-27', '_col3': '51', '_col4': '178', '_col5': '6', '_col6': '-76.0', '_col7': '762.0'}, {'_col1': '194', '_col2': '2012-09-28', '_col3': '52', '_col4': '179', '_col5': '6', '_col6': '-74.0', '_col7': '762.0'}, {'_col1': '195', '_col2': '2012-09-29', '_col3': '53', '_col4': '179', '_col5': '6', '_col6': '-71.0', '_col7': '764.0'}, {'_col1': '196', '_col2': '2012-09-30', '_col3': '54', '_col4': '180', '_col5': '7', '_col6': '-72.0', '_col7': '766.0'}, {'_col1': '197', '_col2': '2012-10-01', '_col3': '55', '_col4': '180', '_col5': '7', '_col6': '-74.0', '_col7': '766.0'}, {'_col1': '198', '_col2': '2012-10-02', '_col3': '56', '_col4': '181', '_col5': '7', '_col6': '-73.0', '_col7': '768.0'}, {'_col1': '199', '_col2': '2012-10-03', '_col3': '57', '_col4': '181', '_col5': '7', '_col6': '-73.0', '_col7': '769.0'}, {'_col1': '200', '_col2': '2012-10-04', '_col3': '58', '_col4': '182', '_col5': '7', '_col6': '-74.0', '_col7': '769.0'}, {'_col1': '201', '_col2': '2012-10-05', '_col3': '59', '_col4': '183', '_col5': '7', '_col6': '-76.0', '_col7': '771.0'}, {'_col1': '202', '_col2': '2012-10-06', '_col3': '60', '_col4': '183', '_col5': '7', '_col6': '-75.0', '_col7': '772.0'}, {'_col1': '203', '_col2': '2012-10-07', '_col3': '61', '_col4': '184', '_col5': '7', '_col6': '-72.0', '_col7': '772.0'}, {'_col1': '204', '_col2': '2012-10-08', '_col3': '62', '_col4': '184', '_col5': '7', '_col6': '-72.0', '_col7': '774.0'}, {'_col1': '205', '_col2': '2012-10-09', '_col3': '63', '_col4': '185', '_col5': '7', '_col6': '-73.0', '_col7': '775.0'}, {'_col1': '206', '_col2': '2012-10-10', '_col3': '64', '_col4': '186', '_col5': '7', '_col6': '-74.0', '_col7': '776.0'}, {'_col1': '207', '_col2': '2012-10-11', '_col3': '65', '_col4': '186', '_col5': '7', '_col6': '-72.0', '_col7': '777.0'}, {'_col1': '208', '_col2': '2012-10-12', '_col3': '66', '_col4': '187', '_col5': '7', '_col6': '-73.0', '_col7': '778.0'}, {'_col1': '209', '_col2': '2012-10-13', '_col3': '67', '_col4': '187', '_col5': '7', '_col6': '-73.0', '_col7': '780.0'}, {'_col1': '210', '_col2': '2012-10-14', '_col3': '68', '_col4': '188', '_col5': '7', '_col6': '-71.0', '_col7': '781.0'}, {'_col1': '211', '_col2': '2012-10-15', '_col3': '69', '_col4': '189', '_col5': '7', '_col6': '-73.0', '_col7': '778.0'}, {'_col1': '212', '_col2': '2012-10-17', '_col3': '70', '_col4': '189', '_col5': '7', '_col6': '-72.0', '_col7': '783.0'}, {'_col1': '213', '_col2': '2012-10-18', '_col3': '71', '_col4': '190', '_col5': '7', '_col6': '-71.0', '_col7': '784.0'}, {'_col1': '214', '_col2': '2012-10-19', '_col3': '72', '_col4': '190', '_col5': '7', '_col6': '-73.0', '_col7': '785.0'}, {'_col1': '215', '_col2': '2012-10-20', '_col3': '73', '_col4': '191', '_col5': '7', '_col6': '-70.0', '_col7': '788.0'}, {'_col1': '216', '_col2': '2012-10-21', '_col3': '74', '_col4': '192', '_col5': '7', '_col6': '-72.0', '_col7': '790.0'}, {'_col1': '217', '_col2': '2012-10-22', '_col3': '75', '_col4': '192', '_col5': '7', '_col6': '-73.0', '_col7': '791.0'}, {'_col1': '218', '_col2': '2012-10-23', '_col3': '76', '_col4': '193', '_col5': '7', '_col6': '-73.0', '_col7': '792.0'}, {'_col1': '219', '_col2': '2012-10-24', '_col3': '77', '_col4': '193', '_col5': '7', '_col6': '-71.0', '_col7': '792.0'}, {'_col1': '220', '_col2': '2012-10-25', '_col3': '78', '_col4': '194', '_col5': '7', '_col6': '-71.0', '_col7': '793.0'}, {'_col1': '221', '_col2': '2012-10-26', '_col3': '79', '_col4': '195', '_col5': '7', '_col6': '-73.0', '_col7': '795.0'}, {'_col1': '222', '_col2': '2012-10-27', '_col3': '80', '_col4': '195', '_col5': '7', '_col6': '-70.0', '_col7': '796.0'}, {'_col1': '223', '_col2': '2012-10-28', '_col3': '81', '_col4': '196', '_col5': '7', '_col6': '-72.0', '_col7': '798.0'}, {'_col1': '224', '_col2': '2012-10-29', '_col3': '82', '_col4': '196', '_col5': '7', '_col6': '-72.0', '_col7': '799.0'}, {'_col1': '225', '_col2': '2012-10-30', '_col3': '83', '_col4': '197', '_col5': '7', '_col6': '-72.0', '_col7': '801.0'}, {'_col1': '226', '_col2': '2012-10-31', '_col3': '84', '_col4': '198', '_col5': '7', '_col6': '-70.0', '_col7': '801.0'}, {'_col1': '227', '_col2': '2012-11-01', '_col3': '85', '_col4': '198', '_col5': '7', '_col6': '-71.0', '_col7': '805.0'}, {'_col1': '228', '_col2': '2012-11-02', '_col3': '86', '_col4': '199', '_col5': '7', '_col6': '-71.0', '_col7': '808.0'}, {'_col1': '229', '_col2': '2012-11-03', '_col3': '87', '_col4': '199', '_col5': '7', '_col6': '-70.0', '_col7': '808.0'}, {'_col1': '230', '_col2': '2012-11-04', '_col3': '88', '_col4': '200', '_col5': '7', '_col6': '-70.0', '_col7': '811.0'}, {'_col1': '231', '_col2': '2012-11-05', '_col3': '89', '_col4': '201', '_col5': '7', '_col6': '-73.0', '_col7': '813.0'}, {'_col1': '233', '_col2': '2012-11-06', '_col3': '90', '_col4': '201', '_col5': '7', '_col6': '-71.0', '_col7': '813.0'}, {'_col1': '234', '_col2': '2012-11-07', '_col3': '91', '_col4': '202', '_col5': '7', '_col6': '-74.0', '_col7': '817.0'}, {'_col1': '235', '_col2': '2012-11-08', '_col3': '92', '_col4': '202', '_col5': '7', '_col6': '-74.0', '_col7': '820.0'}, {'_col1': '236', '_col2': '2012-11-09', '_col3': '93', '_col4': '203', '_col5': '7', '_col6': '-72.0', '_col7': '819.0'}, {'_col1': '237', '_col2': '2012-11-10', '_col3': '94', '_col4': '204', '_col5': '7', '_col6': '-70.0', '_col7': '822.0'}, {'_col1': '238', '_col2': '2012-11-11', '_col3': '95', '_col4': '204', '_col5': '7', '_col6': '-68.0', '_col7': '822.0'}, {'_col1': '239', '_col2': '2012-11-12', '_col3': '96', '_col4': '205', '_col5': '7', '_col6': '-71.0', '_col7': '826.0'}, {'_col1': '240', '_col2': '2012-11-13', '_col3': '97', '_col4': '206', '_col5': '7', '_col6': '-68.0', '_col7': '828.0'}, {'_col1': '241', '_col2': '2012-11-14', '_col3': '98', '_col4': '206', '_col5': '7', '_col6': '-68.0', '_col7': '828.0'}, {'_col1': '242', '_col2': '2012-11-15', '_col3': '99', '_col4': '207', '_col5': '7', '_col6': '-68.0', '_col7': '829.0'}, {'_col1': '3', '_col2': '2012-11-16', '_col3': '100', '_col4': '207', '_col5': '7', '_col6': '-66.0', '_col7': '829.0'}, {'_col1': '4', '_col2': '2012-11-17', '_col3': '101', '_col4': '208', '_col5': '7', '_col6': '-65.0', '_col7': '830.0'}, {'_col1': '5', '_col2': '2012-11-18', '_col3': '102', '_col4': '209', '_col5': '7', '_col6': '-67.0', '_col7': '833.0'}, {'_col1': '6', '_col2': '2012-11-19', '_col3': '103', '_col4': '209', '_col5': '7', '_col6': '-66.0', '_col7': '836.0'}, {'_col1': '7', '_col2': '2012-11-20', '_col3': '104', '_col4': '210', '_col5': '8', '_col6': '-67.0', '_col7': '838.0'}, {'_col1': '8', '_col2': '2012-11-21', '_col3': '105', '_col4': '211', '_col5': '8', '_col6': '-66.0', '_col7': '839.0'}, {'_col1': '9', '_col2': '2012-11-23', '_col3': '106', '_col4': '211', '_col5': '8', '_col6': '-66.0', '_col7': '841.0'}, {'_col1': '10', '_col2': '2012-11-24', '_col3': '107', '_col4': '212', '_col5': '8', '_col6': '-66.0', '_col7': '844.0'}, {'_col1': '11', '_col2': '2012-11-25', '_col3': '108', '_col4': '212', '_col5': '8', '_col6': '-65.0', '_col7': '845.0'}, {'_col1': '12', '_col2': '2012-11-26', '_col3': '109', '_col4': '213', '_col5': '8', '_col6': '-64.0', '_col7': '844.0'}, {'_col1': '14', '_col2': '2012-11-27', '_col3': '110', '_col4': '214', '_col5': '8', '_col6': '-65.0', '_col7': '848.0'}, {'_col1': '15', '_col2': '2012-11-28', '_col3': '111', '_col4': '214', '_col5': '8', '_col6': '-66.0', '_col7': '849.0'}, {'_col1': '16', '_col2': '2012-11-29', '_col3': '112', '_col4': '215', '_col5': '8', '_col6': '-65.0', '_col7': '852.0'}, {'_col1': '17', '_col2': '2012-11-30', '_col3': '113', '_col4': '216', '_col5': '8', '_col6': '-66.0', '_col7': '857.0'}, {'_col1': '18', '_col2': '2012-12-01', '_col3': '114', '_col4': '216', '_col5': '8', '_col6': '-69.0', '_col7': '857.0'}, {'_col1': '19', '_col2': '2012-12-02', '_col3': '115', '_col4': '217', '_col5': '8', '_col6': '-66.0', '_col7': '857.0'}, {'_col1': '20', '_col2': '2012-12-03', '_col3': '116', '_col4': '217', '_col5': '8', '_col6': '-67.0', '_col7': '859.0'}, {'_col1': '21', '_col2': '2012-12-04', '_col3': '117', '_col4': '218', '_col5': '8', '_col6': '-66.0', '_col7': '861.0'}, {'_col1': '22', '_col2': '2012-12-05', '_col3': '118', '_col4': '219', '_col5': '8', '_col6': '-65.0', '_col7': '864.0'}, {'_col1': '23', '_col2': '2012-12-06', '_col3': '119', '_col4': '219', '_col5': '8', '_col6': '-66.0', '_col7': '866.0'}, {'_col1': '25', '_col2': '2012-12-07', '_col3': '120', '_col4': '220', '_col5': '8', '_col6': '-67.0', '_col7': '867.0'}, {'_col1': '26', '_col2': '2012-12-08', '_col3': '121', '_col4': '221', '_col5': '8', '_col6': '-66.0', '_col7': '869.0'}, {'_col1': '27', '_col2': '2012-12-09', '_col3': '122', '_col4': '221', '_col5': '8', '_col6': '-65.0', '_col7': '869.0'}, {'_col1': '28', '_col2': '2012-12-10', '_col3': '123', '_col4': '222', '_col5': '8', '_col6': '-66.0', '_col7': '875.0'}, {'_col1': '29', '_col2': '2012-12-11', '_col3': '124', '_col4': '223', '_col5': '8', '_col6': '-66.0', '_col7': '876.0'}, {'_col1': '30', '_col2': '2012-12-12', '_col3': '125', '_col4': '223', '_col5': '8', '_col6': '-68.0', '_col7': '880.0'}, {'_col1': '31', '_col2': '2012-12-13', '_col3': '126', '_col4': '224', '_col5': '8', '_col6': '-66.0', '_col7': '880.0'}, {'_col1': '32', '_col2': '2012-12-14', '_col3': '127', '_col4': '224', '_col5': '8', '_col6': '-67.0', '_col7': '884.0'}, {'_col1': '33', '_col2': '2012-12-15', '_col3': '128', '_col4': '225', '_col5': '8', '_col6': '-67.0', '_col7': '883.0'}, {'_col1': '34', '_col2': '2012-12-16', '_col3': '129', '_col4': '226', '_col5': '8', '_col6': '-65.0', '_col7': '886.0'}, {'_col1': '36', '_col2': '2012-12-17', '_col3': '130', '_col4': '226', '_col5': '8', '_col6': '-65.0', '_col7': '888.0'}, {'_col1': '37', '_col2': '2012-12-18', '_col3': '131', '_col4': '227', '_col5': '8', '_col6': '-65.0', '_col7': '889.0'}, {'_col1': '38', '_col2': '2012-12-19', '_col3': '132', '_col4': '228', '_col5': '8', '_col6': '-65.0', '_col7': '890.0'}, {'_col1': '39', '_col2': '2012-12-20', '_col3': '133', '_col4': '228', '_col5': '8', '_col6': '-65.0', '_col7': '891.0'}, {'_col1': '40', '_col2': '2012-12-21', '_col3': '134', '_col4': '229', '_col5': '8', '_col6': '-67.0', '_col7': '893.0'}, {'_col1': '41', '_col2': '2012-12-22', '_col3': '135', '_col4': '230', '_col5': '8', '_col6': '-65.0', '_col7': '894.0'}, {'_col1': '42', '_col2': '2012-12-23', '_col3': '136', '_col4': '230', '_col5': '8', '_col6': '-65.0', '_col7': '897.0'}, {'_col1': '43', '_col2': '2012-12-24', '_col3': '137', '_col4': '231', '_col5': '8', '_col6': '-64.0', '_col7': '896.0'}, {'_col1': '44', '_col2': '2012-12-25', '_col3': '138', '_col4': '232', '_col5': '8', '_col6': '-65.0', '_col7': '899.0'}, {'_col1': '45', '_col2': '2012-12-26', '_col3': '139', '_col4': '232', '_col5': '8', '_col6': '-66.0', '_col7': '899.0'}, {'_col1': '47', '_col2': '2012-12-27', '_col3': '140', '_col4': '233', '_col5': '8', '_col6': '-66.0', '_col7': '903.0'}, {'_col1': '48', '_col2': '2012-12-28', '_col3': '141', '_col4': '233', '_col5': '8', '_col6': '-64.0', '_col7': '904.0'}, {'_col1': '49', '_col2': '2012-12-29', '_col3': '142', '_col4': '234', '_col5': '8', '_col6': '-65.0', '_col7': '906.0'}, {'_col1': '50', '_col2': '2012-12-31', '_col3': '143', '_col4': '235', '_col5': '8', '_col6': '-63.0', '_col7': '908.0'}, {'_col1': '51', '_col2': '2013-01-01', '_col3': '144', '_col4': '235', '_col5': '8', '_col6': '-64.0', '_col7': '907.0'}, {'_col1': '52', '_col2': '2013-01-02', '_col3': '145', '_col4': '236', '_col5': '8', '_col6': '-64.0', '_col7': '909.0'}, {'_col1': '53', '_col2': '2013-01-03', '_col3': '146', '_col4': '237', '_col5': '8', '_col6': '-65.0', '_col7': '908.0'}, {'_col1': '54', '_col2': '2013-01-04', '_col3': '147', '_col4': '237', '_col5': '8', '_col6': '-65.0', '_col7': '914.0'}, {'_col1': '55', '_col2': '2013-01-05', '_col3': '148', '_col4': '238', '_col5': '8', '_col6': '-65.0', '_col7': '912.0'}, {'_col1': '56', '_col2': '2013-01-06', '_col3': '149', '_col4': '239', '_col5': '8', '_col6': '-65.0', '_col7': '914.0'}, {'_col1': '58', '_col2': '2013-01-07', '_col3': '150', '_col4': '239', '_col5': '8', '_col6': '-64.0', '_col7': '913.0'}, {'_col1': '59', '_col2': '2013-01-08', '_col3': '151', '_col4': '240', '_col5': '9', '_col6': '-65.0', '_col7': '915.0'}, {'_col1': '60', '_col2': '2013-01-09', '_col3': '152', '_col4': '241', '_col5': '9', '_col6': '-63.0', '_col7': '914.0'}, {'_col1': '61', '_col2': '2013-01-10', '_col3': '153', '_col4': '241', '_col5': '9', '_col6': '-65.0', '_col7': '915.0'}, {'_col1': '62', '_col2': '2013-01-11', '_col3': '154', '_col4': '242', '_col5': '9', '_col6': '-65.0', '_col7': '917.0'}, {'_col1': '63', '_col2': '2013-01-12', '_col3': '155', '_col4': '243', '_col5': '9', '_col6': '-64.0', '_col7': '917.0'}, {'_col1': '64', '_col2': '2013-01-13', '_col3': '156', '_col4': '243', '_col5': '9', '_col6': '-65.0', '_col7': '922.0'}, {'_col1': '65', '_col2': '2013-01-14', '_col3': '157', '_col4': '244', '_col5': '9', '_col6': '-64.0', '_col7': '920.0'}, {'_col1': '66', '_col2': '2013-01-15', '_col3': '158', '_col4': '245', '_col5': '9', '_col6': '-66.0', '_col7': '922.0'}, {'_col1': '67', '_col2': '2013-01-16', '_col3': '159', '_col4': '245', '_col5': '9', '_col6': '-65.0', '_col7': '918.0'}, {'_col1': '69', '_col2': '2013-01-17', '_col3': '160', '_col4': '246', '_col5': '9', '_col6': '-67.0', '_col7': '919.0'}, {'_col1': '70', '_col2': '2013-01-18', '_col3': '161', '_col4': '246', '_col5': '9', '_col6': '-65.0', '_col7': '919.0'}, {'_col1': '71', '_col2': '2013-01-19', '_col3': '162', '_col4': '247', '_col5': '9', '_col6': '-65.0', '_col7': '919.0'}, {'_col1': '72', '_col2': '2013-01-20', '_col3': '163', '_col4': '248', '_col5': '9', '_col6': '-65.0', '_col7': '919.0'}, {'_col1': '73', '_col2': '2013-01-21', '_col3': '164', '_col4': '248', '_col5': '9', '_col6': '-64.0', '_col7': '919.0'}, {'_col1': '74', '_col2': '2013-01-22', '_col3': '165', '_col4': '249', '_col5': '9', '_col6': '-65.0', '_col7': '922.0'}, {'_col1': '75', '_col2': '2013-01-23', '_col3': '166', '_col4': '250', '_col5': '9', '_col6': '-65.0', '_col7': '922.0'}, {'_col1': '76', '_col2': '2013-01-24', '_col3': '167', '_col4': '250', '_col5': '9', '_col6': '-65.0', '_col7': '920.0'}, {'_col1': '77', '_col2': '2013-01-25', '_col3': '168', '_col4': '251', '_col5': '9', '_col6': '-66.0', '_col7': '923.0'}, {'_col1': '78', '_col2': '2013-01-26', '_col3': '169', '_col4': '252', '_col5': '9', '_col6': '-66.0', '_col7': '922.0'}, {'_col1': '80', '_col2': '2013-01-27', '_col3': '170', '_col4': '252', '_col5': '9', '_col6': '-66.0', '_col7': '925.0'}, {'_col1': '81', '_col2': '2013-01-28', '_col3': '171', '_col4': '253', '_col5': '9', '_col6': '-67.0', '_col7': '925.0'}, {'_col1': '82', '_col2': '2013-01-29', '_col3': '172', '_col4': '254', '_col5': '9', '_col6': '-67.0', '_col7': '923.0'}, {'_col1': '83', '_col2': '2013-01-30', '_col3': '173', '_col4': '254', '_col5': '9', '_col6': '-67.0', '_col7': '920.0'}, {'_col1': '84', '_col2': '2013-01-31', '_col3': '174', '_col4': '255', '_col5': '9', '_col6': '-67.0', '_col7': '921.0'}, {'_col1': '85', '_col2': '2013-02-01', '_col3': '175', '_col4': '256', '_col5': '9', '_col6': '-68.0', '_col7': '921.0'}, {'_col1': '86', '_col2': '2013-02-02', '_col3': '176', '_col4': '256', '_col5': '9', '_col6': '-67.0', '_col7': '920.0'}, {'_col1': '87', '_col2': '2013-02-03', '_col3': '177', '_col4': '257', '_col5': '9', '_col6': '-66.0', '_col7': '921.0'}, {'_

In [7]:
# Create a Pandas DataFrame by using the list of rows and a list of the column names
import pandas as pd

# Assuming mars_facts_list is your list of dictionaries
mars_df = pd.DataFrame(mars_facts, columns=['_col1', '_col2', '_col3', '_col4', '_col5', '_col6', '_col7'])
column_name_mapping = {
    '_col1': 'id',
    '_col2': 'terrestrial_date',
    '_col3': 'sol',
    '_col4': 'ls',
    '_col5': 'month',
    '_col6': 'min_temp',
    '_col7': 'pressure'
}
mars_df.rename(columns=column_name_mapping, inplace=True)

mars_df = mars_df.drop(index=0)

In [8]:
# Confirm DataFrame was created successfully
print(mars_df)

        id terrestrial_date   sol   ls month min_temp pressure
1        2       2012-08-16    10  155     6    -75.0    739.0
2       13       2012-08-17    11  156     6    -76.0    740.0
3       24       2012-08-18    12  156     6    -76.0    741.0
4       35       2012-08-19    13  157     6    -74.0    732.0
5       46       2012-08-20    14  157     6    -74.0    740.0
...    ...              ...   ...  ...   ...      ...      ...
1863  1889       2018-02-23  1973  133     5    -78.0    730.0
1864  1892       2018-02-24  1974  134     5    -77.0    729.0
1865  1894       2018-02-25  1975  134     5    -76.0    729.0
1866  1893       2018-02-26  1976  135     5    -77.0    728.0
1867  1895       2018-02-27  1977  135     5    -77.0    727.0

[1867 rows x 7 columns]

### Step 4: Prepare Data for Analysis

Examine the data types that are currently associated with each column. If necessary, cast (or convert) the data to the appropriate `datetime`, `int`, or `float` data types.

  > **Hint** You can use the Pandas `astype` and `to_datetime` methods to accomplish this task.

In [22]:
# Examine data type of each column
print(mars_df.dtypes)

id                  object
terrestrial_date    object
sol                 object
ls                  object
month               object
min_temp            object
pressure            object
dtype: object

In [27]:
# Change data types for data analysis
mars_df = mars_df.astype({'id': 'int', 'sol': 'int', 'ls': 'int', 'month' : 'int', 'min_temp':'float', 'pressure' : 'float'})
mars_df['terrestrial_date'] = pd.to_datetime(mars_df['terrestrial_date'])

In [28]:
# Confirm type changes were successful by examining data types again
print(mars_df.dtypes)

id                           int32
terrestrial_date    datetime64[ns]
sol                          int32
ls                           int32
month                        int32
min_temp                   float64
pressure                   float64
dtype: object

### Step 5: Analyze the Data

Analyze your dataset by using Pandas functions to answer the following questions:

1. How many months exist on Mars?
2. How many Martian (and not Earth) days worth of data exist in the scraped dataset?
3. What are the coldest and the warmest months on Mars (at the location of Curiosity)? To answer this question:
    * Find the average the minimum daily temperature for all of the months.
    * Plot the results as a bar chart.
4. Which months have the lowest and the highest atmospheric pressure on Mars? To answer this question:
    * Find the average the daily atmospheric pressure of all the months.
    * Plot the results as a bar chart.
5. About how many terrestrial (Earth) days exist in a Martian year? To answer this question:
    * Consider how many days elapse on Earth in the time that Mars circles the Sun once.
    * Visually estimate the result by plotting the daily minimum temperature.

In [12]:
# 1. How many months are there on Mars?

In [13]:
# 2. How many Martian days' worth of data are there?

In [14]:
# 3. What is the average low temperature by month?

In [15]:
# Plot the average temperature by month

In [16]:
# Identify the coldest and hottest months in Curiosity's location

In [17]:
# 4. Average pressure by Martian month

In [18]:
# Plot the average pressure by month

In [19]:
# 5. How many terrestrial (earth) days are there in a Martian year?

On average, the third month has the coldest minimum temperature on Mars, and the eighth month is the warmest. But it is always very cold there in human terms!

Atmospheric pressure is, on average, lowest in the sixth month and highest in the ninth.

The distance from peak to peak is roughly 1425-750, or 675 days. A year on Mars appears to be about 675 days from the plot. Internet search confirms that a Mars year is equivalent to 687 earth days.

### Step 6: Save the Data

Export the DataFrame to a CSV file.

In [20]:
# Write the data to a CSV

In [21]:
browser.quit()